source 'https://rubygems.org'

gem 'rails', '4.1.0'

gem 'active_model_serializers'
gem 'pg'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'spring',        group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
